### ISSUE TITLE
关于机器学习测试

### ISSUE THREAD

**Issue by requireonce** [TommyLemon/APIAuto#10]
您好 这个工具很不错
不过有一个意见机器学习测试中没有使用任何机器学习的算法,直接说是机器学习测试这样很不严谨

**Comment by TommyLemon** [comment]
算法是完全是我自己写的，没有用任何第三方的库
https://github.com/TommyLemon/APIAuto/blob/master/apijson/README.md#%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E6%B5%8B%E8%AF%95--comparewithstandard-updatestandard

QECon 大会上有详细介绍
https://www.bilibili.com/video/BV1yv411p7Y4

被 QECon 主办方把我从包括 BAT、字节跳动、京东、华为等各大厂商的几十个专家/架构师的讲师中挑了出来，和华为云副总裁并列到一个海报。
https://appp21noylt4551.pc.xiaoe-tech.com/detail/p_60b9fff3e4b0c726421c3c8e/6?fromH5=true
