### ISSUE TITLE
前端页面请求404

### ISSUE THREAD

**Issue by hxdwd** [TommyLemon/APIAuto#14]
把项目下了下来，后端启动的是springboot demo项目，前端页面的数据库配置也改了，为啥请求错误
看路径请求的是/delegate，没有这个接口所以报错404
![image](https://user-images.githubusercontent.com/52123579/144950373-97edd7df-c212-4635-8256-d0105ddfe28b.png)

下面是通过idea请求，是正常的
![image](https://user-images.githubusercontent.com/52123579/144950485-056aa5cb-4a1c-4825-a180-7034cfd0f5b3.png)

**Comment by TommyLemon** [comment]
只有 APIJSONBoot 系列的 Demo 中 DemoController 才实现了 /delegate 代理接口
https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server

**Comment by hxdwd** [comment]
已解决，感谢
