### ISSUE TITLE
APIJSONBoot-MultiDataSource工程启动报错：  !!!! 查询权限配置异常 !!! Unknown column 'apijson' in 'where clause'

### ISSUE THREAD

**Issue by lesliechueng** [TommyLemon/APIAuto#18]
【标题】：Unknown column 'apijson' in 'where clause' 
【内容】：**环境信息**  
 系统: Windows 10 10.0 
 数据库: MYSQL 5.7.22 
 JDK: 1.8.0_181 amd64 
 APIJSON: 5.0.0

**问题描述**
Unknown column 'apijson' in 'where clause' 

2022-04-21 07:46:24.770: APIJSONRouterVerifier.ERROR: 
接口映射配置测试未通过！
请修改 Document 表里的记录！
保证前端看到的接口映射配置文档是正确的并且能正常使用！！！

原因：
查询权限配置异常 !

**Comment by lesliechueng** [comment]
排查发现会因为数据库脚本该表不包含apijson子弹，使用的脚本是APIJSON-Demo-master\MySQL下的sys.sql

**Comment by TommyLemon** [comment]
感谢反馈，不过 issue 提错了地方，APIAuto 不是 APIJSON
https://github.com/Tencent/APIJSON/issues/36
