### ISSUE TITLE
【UnitAuto】-单元测试，方法的入参是对象，不能自动生成对象属性值吗？

### ISSUE THREAD

**Issue by 1134041701** [TommyLemon/APIAuto#30]
入参为User对象
![image](https://user-images.githubusercontent.com/64843785/225495573-f9b94625-6c8f-4ad4-9ea8-2d777f3502d8.png)

**Comment by TommyLemon** [comment]
目前还不支持，需要反射调用 class.getFields ，然后调用 MethodUtil.mockValue 为每个成员变量赋值

**Comment by 1134041701** [comment]
在网页编辑 User 对象，然后点右上角中间图标按钮 [上传/分享] 保存
点击上传----没有请求后端接口
点击分享----看了表数据没有修改新增数据
不知道这里的上传和分享是同步修改了哪张表数据

**Comment by TommyLemon** [comment]
你漏了前面的步骤，一步步来，有问题把过程截屏发出来方便诊断

**Comment by TommyLemon** [comment]
> 目前还不支持，需要反射调用 class.getFields ，然后调用 MethodUtil.mockValue 为每个成员变量赋值。 https://www.likecs.com/show-307761888.html
> 
> 不改源码的话可以导入后，点开用例，直接在网页编辑 User 对象，然后点右上角中间图标按钮 [上传/分享] 保存

2.9.0 已经支持
https://github.com/TommyLemon/UnitAuto/releases/tag/2.9.0
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/5738175/225667412-175b4b4d-d8bf-477a-9bc4-dfca3bd198ca.png">

**Comment by 1134041701** [comment]
好的  感谢

**Comment by 1134041701** [comment]
对象入参的前端控制台报错，功能上没发现啥问题
![image](https://user-images.githubusercontent.com/64843785/227146490-3f1e6a60-caa7-4633-bd82-60b9a245180b.png)

**Comment by 1134041701** [comment]
好的  感谢解答
