### ISSUE TITLE
APIAuto优化建议

### ISSUE THREAD

**Issue by chaolei-peng** [TommyLemon/APIAuto#6]
![image](https://user-images.githubusercontent.com/16797866/101136932-ffacec00-3648-11eb-832c-6ef0a8223217.png)
描述：正常情况鼠标移动至标记圈内时会显示下拉菜单项，但经常会出现鼠标移动到下拉菜单位置时，菜单项就消失了，目测应该是在鼠标经过上面和下拉框菜单有一个很小的边框距离导致失去焦点执行了隐藏，还请优化一下，致谢！

**Comment by TommyLemon** [comment]
感谢建议

**Comment by TommyLemon** [comment]
已解决
https://github.com/TommyLemon/APIAuto/commit/1471312cede6f1092cc50cd60fca3c152f7421a0
